#!/usr/bin/bash

SCR=$(realpath $(dirname ${BASH_SOURCE[0]}))
LEAF=_env$(date -u +%s)

[[ $(pwd) =~ $TMP ]] || cd $TMP

printf "${GREEN}Backup tag?: "
read tag
printf "${NC}"

[[ $BACKUP_PATH ]]    || export BACKUP_PATH="$HOME/code/unnamed"
[[ -d $BACKUP_PATH ]] || ( mkdir -p $BACKUP_PATH && chmod 700 $BACKUP_PATH -R )

export LEAF="$tag$LEAF"

printf "${CYAN}$SCR${NC}\n"
tar -cjf $LEAF.tbz2 .envrc .gitignore backup_env backups .git
gpg -se -r $GPG $SCR/$LEAF.*
mv *.gpg $BACKUP_PATH
rm $LEAF.* 
export BACKUP_PATH
echo -e "${Yel}$BACKUP_PATH${NC}"
